# Generated by Django 3.2.16 on 2025-11-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='output_order',
        ),
    ]
